### ISSUE TITLE
Can't handle currencies with 1000 subdivisions

### ISSUE THREAD

**Issue by agilbertson1977** [dleitee/walletjs#1]
Given that the normalize and denormalize functions, as well as some functions that cause rounding, are hard-coded to assume that the currency in use is subdivided into exactly 100 parts, it will be difficult to extend this library to handle currencies that subdivide further, such as the Kuwaiti dinar (which subdivides to 1000 fils or Bitcoins which subdivides to 100000000 satoshis.

**Comment by dleitee** [comment]
Hey, @agilbertson1977.
Glad you said it.
I didn't know about it. We could have a setting where you pass the value, what name would you give to this setting? numberOfSubdivision?

**Comment by agilbertson1977** [comment]
numberOfSubdivisions is a good (if long) name, and I can't think of a shorter one that's still accurate to the purpose of the field.

I can see two potential approaches to resolving this issue: One is to associate the numberOfSubdivisions with the currency (although that means you have to add data to the currency array), which lets you be sure that the correct value is selected for each currency but requires that someone maintain the code (and I suspect a lot of currencies will need to be added if you want it to see widespread adoption); the other is to add a numberOfSubdivisions field to the constructor, which is more flexible and doesn't rely on someone maintaining this code but could run into issues when someone puts in an incorrect value (or just a "funny" value, like 3, which will result in a value 1/3 creating a result if .3 repeating) into that field.

**Comment by dleitee** [comment]
@agilbertson1977 I created this approach to work with currency fractionals. Could you see? #2
